In [1]:
import pandas as pd
pd.set_option('display.max_columns',None)

In [2]:
credit_data=pd.read_csv(r"C:\Users\aman\programming\ml projects\dataset\movie recommendation deployment\credits\credits.csv",encoding='latin-1')

In [3]:
credit_data.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [4]:
keyword_data=pd.read_csv(r"C:\Users\aman\programming\ml projects\dataset\movie recommendation deployment\keywords\keywords.csv",encoding='latin-1')

In [5]:
keyword_data.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [6]:
movie_data=pd.read_csv(r"C:\Users\aman\programming\ml projects\dataset\movie recommendation deployment\metadata1\movie_metadata.csv",encoding='latin-1')

In [7]:
movie_data.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar√Ç,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End√Ç,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre√Ç,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises√Ç,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens√Ç¬† ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [8]:
movie_data.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [9]:
movie_data=movie_data[['director_name','genres','actor_1_name','actor_2_name','movie_title','actor_3_name','title_year']]

In [10]:
movie_data.head()

,director_name,genres,actor_1_name,actor_2_name,movie_title,actor_3_name,title_year
0,James Cameron,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Avatar√Ç,Wes Studi,2009.0
1,Gore Verbinski,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Pirates of the Caribbean: At World's End√Ç,Jack Davenport,2007.0
2,Sam Mendes,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Spectre√Ç,Stephanie Sigman,2015.0
3,Christopher Nolan,Action|Thriller,Tom Hardy,Christian Bale,The Dark Knight Rises√Ç,Joseph Gordon-Levitt,2012.0
4,Doug Walker,Documentary,Doug Walker,Rob Walker,Star Wars: Episode VII - The Force Awakens√Ç¬† ...,NaN,NaN

In [11]:
movies_metadata=pd.read_csv(r"C:\Users\aman\programming\ml projects\dataset\movie recommendation deployment\metadata2\movies_metadata.csv",encoding='latin-1')

C:\Users\aman\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
movies_metadata.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [13]:
movies_metadata=movies_metadata[['id','genres','original_title','overview','production_companies','tagline','release_date']]

In [14]:
merged_data=credit_data.merge(keyword_data,on='id')

In [15]:
movie_data.head()

,director_name,genres,actor_1_name,actor_2_name,movie_title,actor_3_name,title_year
0,James Cameron,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Avatar√Ç,Wes Studi,2009.0
1,Gore Verbinski,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Pirates of the Caribbean: At World's End√Ç,Jack Davenport,2007.0
2,Sam Mendes,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Spectre√Ç,Stephanie Sigman,2015.0
3,Christopher Nolan,Action|Thriller,Tom Hardy,Christian Bale,The Dark Knight Rises√Ç,Joseph Gordon-Levitt,2012.0
4,Doug Walker,Documentary,Doug Walker,Rob Walker,Star Wars: Episode VII - The Force Awakens√Ç¬† ...,NaN,NaN

In [16]:
lis=[i for i in movies_metadata['id'] if len(i)>7]
lis

['1997-08-20', '2012-09-29', '2014-01-01']

In [17]:
for i in lis:
    index=movies_metadata[movies_metadata['id']==i].index.values
    print(index[0])
    movies_metadata.drop(index[0],inplace=True)

19730
29503
35587

In [18]:
movies_metadata['id']=movies_metadata['id'].apply(lambda x: int(x))

In [19]:
merged_data=merged_data.merge(movies_metadata,on='id')

In [20]:
merged_data.head()

,cast,crew,id,keywords,genres,original_title,overview,production_companies,tagline,release_date
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",NaN,1995-10-30
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Roll the dice and unleash the excitement!,1995-12-15
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Still Yelling. Still Fighting. Still Ready for...,1995-12-22
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Friends are the people who let you be yourself...,1995-12-22
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'id': 35, 'name': 'Comedy'}]",Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Just When His World Is Back To Normal... He's ...,1995-02-10

In [21]:
movie_data.head()

,director_name,genres,actor_1_name,actor_2_name,movie_title,actor_3_name,title_year
0,James Cameron,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Joel David Moore,Avatar√Ç,Wes Studi,2009.0
1,Gore Verbinski,Action|Adventure|Fantasy,Johnny Depp,Orlando Bloom,Pirates of the Caribbean: At World's End√Ç,Jack Davenport,2007.0
2,Sam Mendes,Action|Adventure|Thriller,Christoph Waltz,Rory Kinnear,Spectre√Ç,Stephanie Sigman,2015.0
3,Christopher Nolan,Action|Thriller,Tom Hardy,Christian Bale,The Dark Knight Rises√Ç,Joseph Gordon-Levitt,2012.0
4,Doug Walker,Documentary,Doug Walker,Rob Walker,Star Wars: Episode VII - The Force Awakens√Ç¬† ...,NaN,NaN

In [22]:
movie_data.shape

(5043, 7)

In [23]:
from ast import literal_eval

In [24]:
merged_data['cast']=merged_data['cast'].apply(literal_eval)

In [25]:
def actor_1(x):
    if len(x)==0:
         return " "
    else:
        if 'name' in x[0].keys():
            return x[0]['name']
        else:
            return " "

In [26]:
def actor_2(x):
    if len(x)==0:
         return " "
    else:
        if len(x)>1:
             if 'name' in x[1].keys():
                return x[1]['name']
             else:
                return x[3]['name']
    return " "

In [27]:
def actor_3(x):
    if len(x)==0:
        return " "
    else :
        if len(x)>2:
            if 'name' in x[2].keys():
                return x[2]['name']
            else:
                return x[4]['name']
    return " "

In [28]:
merged_data['actor_1']=merged_data['cast'].apply(actor_1)
merged_data['actor_2']=merged_data['cast'].apply(actor_2)
merged_data['actor_3']=merged_data['cast'].apply(actor_3)

In [29]:
def director(x):
    for i in x:
        if i['job']=='Director':
            return i['name']
        else:
            return ' ' 
    return ' '

In [30]:
merged_data['crew']=merged_data['crew'].apply(literal_eval)

In [31]:
merged_data['Director']=merged_data['crew'].apply(director)

In [32]:
merged_data['Director'][0]

'John Lasseter'

In [33]:
merged_data.head()

,cast,crew,id,keywords,genres,original_title,overview,production_companies,tagline,release_date,actor_1,actor_2,actor_3,Director
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",NaN,1995-10-30,Tom Hanks,Tim Allen,Don Rickles,John Lasseter
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Roll the dice and unleash the excitement!,1995-12-15,Robin Williams,Jonathan Hyde,Kirsten Dunst,
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Still Yelling. Still Fighting. Still Ready for...,1995-12-22,Walter Matthau,Jack Lemmon,Ann-Margret,Howard Deutch
3,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,Friends are the people who let you be yourself...,1995-12-22,Whitney Houston,Angela Bassett,Loretta Devine,Forest Whitaker
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'id': 35, 'name': 'Comedy'}]",Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",Just When His World Is Back To Normal... He's ...,1995-02-10,Steve Martin,Diane Keaton,Martin Short,

In [34]:
merged_data['genres'][0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [35]:
merged_data['genres']=merged_data['genres'].apply(literal_eval)

In [36]:
merged_data['genres'][0]

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [37]:
def genres(x):
    s=' '
    i=0
    if len(x)==0:
        return s
    else:
        while i<len(x):
            if 'name' in x[i].keys():
                s+=" "+x[i]['name']
                i+=1
    return s

In [38]:
merged_data['genre']=merged_data['genres'].apply(genres)

In [39]:
import matplotlib.pyplot as plt

In [40]:
from datetime import datetime

merged_data['release_date']=pd.to_datetime(merged_data['release_date'])
merged_data['release_year']=merged_data['release_date'].dt.year
merged_data['release_year'].dropna(inplace=True,how='any')
merged_data['release_year'].isnull().sum()

In [41]:
merged_data.columns

Index(['cast', 'crew', 'id', 'keywords', 'genres', 'original_title',
       'overview', 'production_companies', 'tagline', 'release_date',
       'actor_1', 'actor_2', 'actor_3', 'Director', 'genre'],
      dtype='object')

In [42]:
merged_data.isnull().sum()

cast                        0
crew                        0
id                          0
keywords                    0
genres                      0
original_title              0
overview                  995
production_companies        4
tagline                 25845
release_date               88
actor_1                     0
actor_2                     0
actor_3                     0
Director                    0
genre                       0
dtype: int64

In [43]:
merged_data=merged_data[['id','original_title','actor_1','actor_2','actor_3','Director','genre']]

In [44]:
merged_data.head()

,id,original_title,actor_1,actor_2,actor_3,Director,genre
0,862,Toy Story,Tom Hanks,Tim Allen,Don Rickles,John Lasseter,Animation Comedy Family
1,8844,Jumanji,Robin Williams,Jonathan Hyde,Kirsten Dunst,,Adventure Fantasy Family
2,15602,Grumpier Old Men,Walter Matthau,Jack Lemmon,Ann-Margret,Howard Deutch,Romance Comedy
3,31357,Waiting to Exhale,Whitney Houston,Angela Bassett,Loretta Devine,Forest Whitaker,Comedy Drama Romance
4,11862,Father of the Bride Part II,Steve Martin,Diane Keaton,Martin Short,,Comedy

In [45]:
movie_data.isnull().sum()

director_name    104
genres             0
actor_1_name       7
actor_2_name      13
movie_title        0
actor_3_name      23
title_year       108
dtype: int64

In [46]:
movie_data['director_name']=movie_data['director_name'].map(lambda x:str(x))

In [47]:
movie_data['director_name']=movie_data['director_name'].map(lambda x:x.replace("NaN"," "))

In [48]:
lis=['actor_1_name','actor_2_name','actor_3_name']
for i in lis:
    movie_data[i]=movie_data[i].map(lambda x:str(x))

In [49]:
lis=['actor_1_name','actor_2_name','actor_3_name']
for i in lis:
    movie_data[i]=movie_data[i].map(lambda x:x.replace("NaN"," "))

In [50]:
import re

In [51]:
movie_data['genres']=movie_data['genres'].map(lambda x:re.sub('\W'," ",x))

In [52]:
movie_data['genres'][:5]

0    Action Adventure Fantasy Sci Fi
1           Action Adventure Fantasy
2          Action Adventure Thriller
3                    Action Thriller
4                        Documentary
Name: genres, dtype: object

In [53]:
movie_data['movie_title']=movie_data['movie_title'].map(lambda x: re.sub('√Ç',' ',x))

In [54]:
movie_data.drop('title_year',inplace=True,axis=1)

In [55]:
movie_data.isnull().sum()

director_name    0
genres           0
actor_1_name     0
actor_2_name     0
movie_title      0
actor_3_name     0
dtype: int64

In [56]:
merged_data.isnull().sum()

id                0
original_title    0
actor_1           0
actor_2           0
actor_3           0
Director          0
genre             0
dtype: int64

In [57]:
merged_data.rename({'original_title':'movie_title','Director':'director_name','genre':'genres','actor_1':'actor_1_name','actor_2':'actor_2_name','actor_3':'actor_3_name'},axis=1,inplace=True)

In [58]:
merged_data.drop('id',axis=1,inplace=True)

In [59]:
merged_data.head()

,movie_title,actor_1_name,actor_2_name,actor_3_name,director_name,genres
0,Toy Story,Tom Hanks,Tim Allen,Don Rickles,John Lasseter,Animation Comedy Family
1,Jumanji,Robin Williams,Jonathan Hyde,Kirsten Dunst,,Adventure Fantasy Family
2,Grumpier Old Men,Walter Matthau,Jack Lemmon,Ann-Margret,Howard Deutch,Romance Comedy
3,Waiting to Exhale,Whitney Houston,Angela Bassett,Loretta Devine,Forest Whitaker,Comedy Drama Romance
4,Father of the Bride Part II,Steve Martin,Diane Keaton,Martin Short,,Comedy

In [60]:
final_data=merged_data.append(movie_data,ignore_index=True)

C:\Users\aman\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [61]:
final_data

,actor_1_name,actor_2_name,actor_3_name,director_name,genres,movie_title
0,Tom Hanks,Tim Allen,Don Rickles,John Lasseter,Animation Comedy Family,Toy Story
1,Robin Williams,Jonathan Hyde,Kirsten Dunst,,Adventure Fantasy Family,Jumanji
2,Walter Matthau,Jack Lemmon,Ann-Margret,Howard Deutch,Romance Comedy,Grumpier Old Men
3,Whitney Houston,Angela Bassett,Loretta Devine,Forest Whitaker,Comedy Drama Romance,Waiting to Exhale
4,Steve Martin,Diane Keaton,Martin Short,,Comedy,Father of the Bride Part II
5,Al Pacino,Robert De Niro,Val Kilmer,Michael Mann,Action Crime Drama Thriller,Heat
6,Harrison Ford,Julia Ormond,Greg Kinnear,Sydney Pollack,Comedy Romance,Sabrina
7,Jonathan Taylor Thomas,Brad Renfro,Rachael Leigh Cook,,Action Adventure Drama Family,Tom and Huck
8,Jean-Claude Van Damme,Powers Boothe,Dorian Harewood,Peter Hyams,Action Adventure Thriller,Sudden Death
9,Pierce Brosnan,Sean Bean,Izabella Scorupco,Martin Campbell,Adventure Action Thriller,GoldenEye
10,Michael Douglas,Annette Bening,Michael J. Fox,,Comedy Drama Romance,The American President
11,Leslie Nielsen,Mel Brooks,Amy Yasbeck,,Comedy Horror,Dracula: Dead and Loving It
12,Kevin Bacon,Bob Hoskins,Bridget Fonda,,Family Animation Adventure,Balto
13,Anthony Hopkins,Joan Allen,Powers Boothe,Oliver Stone,History Drama,Nixon
14,Geena Davis,Matthew Modine,Frank Langella,,Action Adventure,Cutthroat Island
15,Robert De Niro,Sharon Stone,Joe Pesci,Martin Scorsese,Drama Crime,Casino
16,Kate Winslet,Emma Thompson,Hugh Grant,Ang Lee,Drama Romance,Sense and Sensibility
17,Tim Roth,Antonio Banderas,Jennifer Beals,,Crime Comedy,Four Rooms
18,Jim Carrey,Ian McNeice,Simon Callow,Steve Oedekerk,Crime Comedy Adventure,Ace Ventura: When Nature Calls
19,Wesley Snipes,Woody Harrelson,Jennifer Lopez,Joseph Ruben,Action Comedy Crime,Money Train
20,John Travolta,Gene Hackman,Rene Russo,Barry Sonnenfeld,Comedy Thriller Crime,Get Shorty
21,Sigourney Weaver,Holly Hunter,Will Patton,,Drama Thriller,Copycat
22,Sylvester Stallone,Antonio Banderas,Julianne Moore,Richard Donner,Action Adventure Crime Thriller,Assassins
23,Mary Steenburgen,Sean Patrick Flanery,Lance Henriksen,Victor Salva,Drama Fantasy Science Fiction Thriller,Powder
24,Nicolas Cage,Elisabeth Shue,Julian Sands,,Drama Romance,Leaving Las Vegas
25,Laurence Fishburne,Ir√É¬®ne Jacob,Kenneth Branagh,,Drama,Othello
26,Christina Ricci,Rosie O'Donnell,Thora Birch,Lesli Linka Glatter,Comedy Drama Family,Now and Then
27,Amanda Root,Ciar√É¬°n Hinds,Susan Fleetwood,Roger Michell,Drama Romance,Persuasion
28,Ron Perlman,Dominique Pinon,Judith Vittet,Jean-Pierre Jeunet,Fantasy Science Fiction Adventure,La Cit√É¬© des Enfants Perdus
29,Gong Li,Li Bao-Tian,Wang Xiaoxiao,Zhang Yimou,Drama Crime,√¶¬ë¬á√•¬ï¬ä√¶¬ë¬á√Ø¬º¬å√¶¬ë¬á√•¬à¬∞√•¬§¬ñ√•¬©¬Ü√¶¬°¬•
...,...,...,...,...,...,...
51641,Franky G,Panchito G√É¬≥mez,Casper Martinez,Eric Eason,Drama Family,Manito
51642,Matt Frewer,Katharine Isabelle,Michael Par√É¬©,Uwe Boll,Action Crime Thriller,Rampage
51643,Tommy Pallotta,Richard Linklater,Jean Caffeine,Richard Linklater,Comedy Drama,Slacker
51644,Tjasa Ferme,Mikaal Bates,Damon Owlia,Joseph Mazzella,Crime Drama Thriller,Dutch Kills
51645,Kristen Seavey,Suzi Lorraine,Travis Legge,Travis Legge,Comedy Romance,Dry Spell
51646,Shannen Fields,Lisa Arnold,Janet Lee Dapper,Alex Kendrick,Drama,Flywheel
51647,Ashley Tramonte,Brittany Curran,Lindsay MacDonald,Marcus Nispel,Horror Mystery Thriller,Exeter
51648,Robbie Barnes,Alana Kaniewski,Brandon Landers,Brandon Landers,Drama Horror Thriller,The Ridges
51649,Mark Duplass,Katie Aselton,Bari Hyman,Jay Duplass,Comedy Drama Romance,The Puffy Chair
51650,Paul Ogola,Olwenya Maina,Mugambi Nthiga,Jim Chuchu,Drama,Stories of Our Lives
51651,Zoe Lister-Jones,Heather Burns,Ebon Moss-Bachrach,Daryl Wein,Romance,Breaking Upwards
51652,Sean Whalen,Jason Trost,Nick Principe,Jason Trost,Sci Fi Thriller,All Superheroes Must Die
51653,Divine,Mink Stole,Edith Massey,John Waters,Comedy Crime Horror,Pink Flamingos
51654,Maggie Cheung,B√É¬©atrice Dalle,Don McKellar,Olivier Assayas,Drama Music Romance,Clean
51655,Fereshteh Sadre Orafaiy,Nargess Mamizadeh,Mojgan Faramarzi,Jafar Panahi,Drama,The Circle
51656,Patrick O'Donnell,Michael Parle,Emma Eliza Regan,Ivan Kavanagh,Horror,Tin Can Man
51657,K√É¬¥ji Yakusho,Anna Nakagawa,Denden,Kiyoshi Kurosawa,Crime Horror Mystery Thriller,The Cure
51658,Tatiana Suarez-Pico,Michael Cortez,Eric Ambriz,Tadeo Garcia,Drama,On the Downlow
51659,Julianna Pitt,Joe Coffey,John Lucas,Thomas L. Phillips,Comedy Horror Thriller,Sanctuary; Quite a Conundrum
51660,Peter Greene,Stanley B. Herman,James Noble,Ash Baron-Cohen,Crime Drama,Bang
51661,Shane Carruth,David Sullivan,Casey Gooden,Shane Carruth,Drama Sci Fi Thriller,Primer
51662,Ian Gamazon,Edgar Tancangco,Quynn Ton,Neill Dela Llana,Thriller,Cavite
51663,Carlos Gallardo,Peter Marquardt,Consuelo G√É¬≥mez,Robert Rodriguez,Action Crime Drama Romance Thriller,El Mariachi
51664,Richard Jewell,John Considine,Sara Stepnicka,Anthony Vallone,Crime Drama,The Mongol King
51665,Kerry Bish√É¬©,Caitlin FitzGerald,Daniella Pineda,Edward Burns,Comedy Drama,Newlyweds
51666,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith,Comedy Drama,Signed Sealed Delivered
51667,Natalie Zea,Valorie Curry,Sam Underwood,nan,Crime Drama Mystery Thriller,The Following
51668,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds,Drama Horror Thriller,A Plague So Pleasant
51669,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,Comedy Drama Romance,Shanghai Calling
51670,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,Documentary,My Date with Drew

In [62]:
final_data

,actor_1_name,actor_2_name,actor_3_name,director_name,genres,movie_title
0,Tom Hanks,Tim Allen,Don Rickles,John Lasseter,Animation Comedy Family,Toy Story
1,Robin Williams,Jonathan Hyde,Kirsten Dunst,,Adventure Fantasy Family,Jumanji
2,Walter Matthau,Jack Lemmon,Ann-Margret,Howard Deutch,Romance Comedy,Grumpier Old Men
3,Whitney Houston,Angela Bassett,Loretta Devine,Forest Whitaker,Comedy Drama Romance,Waiting to Exhale
4,Steve Martin,Diane Keaton,Martin Short,,Comedy,Father of the Bride Part II
5,Al Pacino,Robert De Niro,Val Kilmer,Michael Mann,Action Crime Drama Thriller,Heat
6,Harrison Ford,Julia Ormond,Greg Kinnear,Sydney Pollack,Comedy Romance,Sabrina
7,Jonathan Taylor Thomas,Brad Renfro,Rachael Leigh Cook,,Action Adventure Drama Family,Tom and Huck
8,Jean-Claude Van Damme,Powers Boothe,Dorian Harewood,Peter Hyams,Action Adventure Thriller,Sudden Death
9,Pierce Brosnan,Sean Bean,Izabella Scorupco,Martin Campbell,Adventure Action Thriller,GoldenEye
10,Michael Douglas,Annette Bening,Michael J. Fox,,Comedy Drama Romance,The American President
11,Leslie Nielsen,Mel Brooks,Amy Yasbeck,,Comedy Horror,Dracula: Dead and Loving It
12,Kevin Bacon,Bob Hoskins,Bridget Fonda,,Family Animation Adventure,Balto
13,Anthony Hopkins,Joan Allen,Powers Boothe,Oliver Stone,History Drama,Nixon
14,Geena Davis,Matthew Modine,Frank Langella,,Action Adventure,Cutthroat Island
15,Robert De Niro,Sharon Stone,Joe Pesci,Martin Scorsese,Drama Crime,Casino
16,Kate Winslet,Emma Thompson,Hugh Grant,Ang Lee,Drama Romance,Sense and Sensibility
17,Tim Roth,Antonio Banderas,Jennifer Beals,,Crime Comedy,Four Rooms
18,Jim Carrey,Ian McNeice,Simon Callow,Steve Oedekerk,Crime Comedy Adventure,Ace Ventura: When Nature Calls
19,Wesley Snipes,Woody Harrelson,Jennifer Lopez,Joseph Ruben,Action Comedy Crime,Money Train
20,John Travolta,Gene Hackman,Rene Russo,Barry Sonnenfeld,Comedy Thriller Crime,Get Shorty
21,Sigourney Weaver,Holly Hunter,Will Patton,,Drama Thriller,Copycat
22,Sylvester Stallone,Antonio Banderas,Julianne Moore,Richard Donner,Action Adventure Crime Thriller,Assassins
23,Mary Steenburgen,Sean Patrick Flanery,Lance Henriksen,Victor Salva,Drama Fantasy Science Fiction Thriller,Powder
24,Nicolas Cage,Elisabeth Shue,Julian Sands,,Drama Romance,Leaving Las Vegas
25,Laurence Fishburne,Ir√É¬®ne Jacob,Kenneth Branagh,,Drama,Othello
26,Christina Ricci,Rosie O'Donnell,Thora Birch,Lesli Linka Glatter,Comedy Drama Family,Now and Then
27,Amanda Root,Ciar√É¬°n Hinds,Susan Fleetwood,Roger Michell,Drama Romance,Persuasion
28,Ron Perlman,Dominique Pinon,Judith Vittet,Jean-Pierre Jeunet,Fantasy Science Fiction Adventure,La Cit√É¬© des Enfants Perdus
29,Gong Li,Li Bao-Tian,Wang Xiaoxiao,Zhang Yimou,Drama Crime,√¶¬ë¬á√•¬ï¬ä√¶¬ë¬á√Ø¬º¬å√¶¬ë¬á√•¬à¬∞√•¬§¬ñ√•¬©¬Ü√¶¬°¬•
...,...,...,...,...,...,...
51641,Franky G,Panchito G√É¬≥mez,Casper Martinez,Eric Eason,Drama Family,Manito
51642,Matt Frewer,Katharine Isabelle,Michael Par√É¬©,Uwe Boll,Action Crime Thriller,Rampage
51643,Tommy Pallotta,Richard Linklater,Jean Caffeine,Richard Linklater,Comedy Drama,Slacker
51644,Tjasa Ferme,Mikaal Bates,Damon Owlia,Joseph Mazzella,Crime Drama Thriller,Dutch Kills
51645,Kristen Seavey,Suzi Lorraine,Travis Legge,Travis Legge,Comedy Romance,Dry Spell
51646,Shannen Fields,Lisa Arnold,Janet Lee Dapper,Alex Kendrick,Drama,Flywheel
51647,Ashley Tramonte,Brittany Curran,Lindsay MacDonald,Marcus Nispel,Horror Mystery Thriller,Exeter
51648,Robbie Barnes,Alana Kaniewski,Brandon Landers,Brandon Landers,Drama Horror Thriller,The Ridges
51649,Mark Duplass,Katie Aselton,Bari Hyman,Jay Duplass,Comedy Drama Romance,The Puffy Chair
51650,Paul Ogola,Olwenya Maina,Mugambi Nthiga,Jim Chuchu,Drama,Stories of Our Lives
51651,Zoe Lister-Jones,Heather Burns,Ebon Moss-Bachrach,Daryl Wein,Romance,Breaking Upwards
51652,Sean Whalen,Jason Trost,Nick Principe,Jason Trost,Sci Fi Thriller,All Superheroes Must Die
51653,Divine,Mink Stole,Edith Massey,John Waters,Comedy Crime Horror,Pink Flamingos
51654,Maggie Cheung,B√É¬©atrice Dalle,Don McKellar,Olivier Assayas,Drama Music Romance,Clean
51655,Fereshteh Sadre Orafaiy,Nargess Mamizadeh,Mojgan Faramarzi,Jafar Panahi,Drama,The Circle
51656,Patrick O'Donnell,Michael Parle,Emma Eliza Regan,Ivan Kavanagh,Horror,Tin Can Man
51657,K√É¬¥ji Yakusho,Anna Nakagawa,Denden,Kiyoshi Kurosawa,Crime Horror Mystery Thriller,The Cure
51658,Tatiana Suarez-Pico,Michael Cortez,Eric Ambriz,Tadeo Garcia,Drama,On the Downlow
51659,Julianna Pitt,Joe Coffey,John Lucas,Thomas L. Phillips,Comedy Horror Thriller,Sanctuary; Quite a Conundrum
51660,Peter Greene,Stanley B. Herman,James Noble,Ash Baron-Cohen,Crime Drama,Bang
51661,Shane Carruth,David Sullivan,Casey Gooden,Shane Carruth,Drama Sci Fi Thriller,Primer
51662,Ian Gamazon,Edgar Tancangco,Quynn Ton,Neill Dela Llana,Thriller,Cavite
51663,Carlos Gallardo,Peter Marquardt,Consuelo G√É¬≥mez,Robert Rodriguez,Action Crime Drama Romance Thriller,El Mariachi
51664,Richard Jewell,John Considine,Sara Stepnicka,Anthony Vallone,Crime Drama,The Mongol King
51665,Kerry Bish√É¬©,Caitlin FitzGerald,Daniella Pineda,Edward Burns,Comedy Drama,Newlyweds
51666,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith,Comedy Drama,Signed Sealed Delivered
51667,Natalie Zea,Valorie Curry,Sam Underwood,nan,Crime Drama Mystery Thriller,The Following
51668,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds,Drama Horror Thriller,A Plague So Pleasant
51669,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia,Comedy Drama Romance,Shanghai Calling
51670,John August,Brian Herzlinger,Jon Gunn,Jon Gunn,Documentary,My Date with Drew

In [65]:
final_data.isnull().sum()

actor_1_name     0
actor_2_name     0
actor_3_name     0
director_name    0
genres           0
movie_title      0
dtype: int64

In [63]:
final_data.to_csv('main_data.csv',index=False)